version: 1
disable_existing_loggers: false
formatters:
  default:
    fmt: '%(asctime)s - %(levelname)s - %(message)s'
  access:
    fmt: '%(asctime)s - %(levelname)s - %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no